### ISSUE TITLE
Filament use is tracked but the spools won't update after printing

### ISSUE THREAD

**Issue by Gagonjh** [OctoFarm/OctoFarm#434] opened 2021-04-14 09:27 UTC
**Describe the bug**
After printing, the weight of the roll is not adjusted. The statistics show the consumption but not in the material overview. 
In addition, the filament overview only shows 34 filaments with all the information. Both errors also occur after the database has been emptied and refilled.
[OctoFarm-FilamentManager (1).log](https://github.com/OctoFarm/OctoFarm/files/6309825/OctoFarm-FilamentManager.1.log)
[OctoFarm-HistoryCollection (1).log](https://github.com/OctoFarm/OctoFarm/files/6309826/OctoFarm-HistoryCollection.1.log)

**Screenshots**
![Screenshot 2021-04-14 111421](https://user-images.githubusercontent.com/49719775/114687264-df3a2000-9d13-11eb-9fb3-785b64c87157.jpg)
![Screenshot 2021-04-14 111357](https://user-images.githubusercontent.com/49719775/114687310-ecefa580-9d13-11eb-8ebe-8a1c8dfc0a2a.jpg)
![Screenshot 2021-04-14 111444](https://user-images.githubusercontent.com/49719775/114687358-f7aa3a80-9d13-11eb-8053-153c3c81a60a.jpg)
![Screenshot 2021-04-14 111645](https://user-images.githubusercontent.com/49719775/114687390-fed14880-9d13-11eb-9491-eca878fbb295.jpg)

System
Raspberry Pi 4 2GB (Server and on one 3D printer)
Raspberry Pi 3 1GB
Klipper as Firmware

Versions (please complete the following information):
Ubuntu (20.04.2 LTS)
OctoFarm (1.1.12)
Octopi (0.18.0)
Octoprint (1.5.3)
Bed Visualizer (1.0.1)
Marlin GCode Documentation (0.12.0)
OctoKlipper (0.3.7)
Preheat Button (0.7.2)
PrintTimeGenius Plugin (2.2.7)
PrusaSlicer Thumbnails (0.1.4)
Themeify (1.2.2)

**Comment by NotExpectedYet** [comment] 2021-04-17 05:21
That is only available when using Filament Manager Plugin. There is no automatic feature without that yet. If you'd like that it needs to be become a Discussion because it comes with caveats, especially around failed prints. 

I will close this as it's not a bug.

**Closed by NotExpectedYet** 2021-04-17 05:21 UTC
Labels: bug

**Comment by NotExpectedYet** [comment] 2021-04-17 10:51
For the other issue please see 

Issues: #353 #358

Both should be fixed on the development branch and will be released with 1.1.13.
